### ISSUE TITLE
Clean up code.

### ISSUE THREAD

**Issue by a-t-0** [HiveMinds-EU/Productivity-phone#20]
- [ ]  Think about the filenaming structure and improve it.
    - [ ] Some files are called `custom_install..` even though they do not install anything.
- [ ] Make code base `shellcheck` compliant.

**Comment by mohitsaxenaknoldus** [comment]
I can work on this.

**Comment by mohitsaxenaknoldus** [comment]
PR: https://github.com/HiveMinds-EU/Productivity-phone/pull/38
