### ISSUE TITLE
Set up continuous integration (CI) for testing the code base.

### ISSUE THREAD

**Issue by a-t-0** [HiveMinds-EU/Productivity-phone#31]
- [ ] Set up CI 
- [ ] Ideally set up self-hosted CI using e.g. GitLab: https://github.com/TruCol/setup_your_own_GitLab_CI
- [ ] Take into account advice given here: https://github.com/HiveMinds-EU/Productivity-setup/issues/1

**Comment by mohitsaxenaknoldus** [comment]
I think I can do this one as well. Also, after this, I can also write a Dockerfile for this.

**Comment by a-t-0** [comment]
Thank you for picking up these tasks! Ideally, the CI would be the https://github.com/TruCol/setup_your_own_GitLab_CI implementation. So I think it would be ideal if you could ensure that works when:
- using the https://github.com/TruCol/setup_your_own_GitLab_CI/blob/master/install_gitlab.sh 
- testing the code using: https://github.com/TruCol/setup_your_own_GitLab_CI/blob/master/test/modular_test_runner.bats (the first time, and not after running it once, waiting for 20 minutes, and then running it again.

However, that is a non-trivial task as the code and the status monitoring function is still a bit complicated. So:
- [ ]  if you want to keep your tempo high, it would be more practical to wait till I fixed that GitLab deployment code, (and have the server running). 
- [ ] Or you can do all the work to set up the CI for this repo, and just wait with running the CI on my GitLab server until I have that deployment fixed

**Comment by mohitsaxenaknoldus** [comment]
PR: https://github.com/HiveMinds-EU/Productivity-phone/pull/37

**Comment by a-t-0** [comment]
Awesome! I have a functional integration test on the GitLab server and GitLab runner CI, which verifies that the CI correctly verifies the build status of a commit in a repository of the deployed GitLab server. It is over [here](https://github.com/TruCol/setup_your_own_GitLab_CI). 

Today, I will ensure this functionality also works for the `install_gitlab.sh` file, and do some general clean-up. After that, I intend to set up the mirrors to that GitLab such that I can get the green CI badges on these repos.
